#!/bin/bash
set -e

apt-get update
apt-get install less locales ssh sudo flash-kernel -y
mv /flash-kernel-db /etc/flash-kernel/db
mv /flash-kernel-cfg /etc/default/flash-kernel
apt-get install -t stretch-backports linux-image-armmp -y
rm -rf /proc/device-tree
echo "orangepi-zero" > /etc/hostname
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo root:1234 | chpasswd
